### ISSUE TITLE
Cannot run locally

### ISSUE THREAD

**Issue by YourHarbour** [AI-Planning/cloud-solver#9]
Hi, I tried as the README that deploys on Heroku, which successes in response to the URL, however when I tried to run locally with command 

`node web.js`

The same URL will always show errors about the phrase of the JSON file.

`SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at _processStopped (/Users/harbour/Desktop/graph_planner/cloud-solver/web.js:190:23)
    at ChildProcess.exithandler (child_process.js:397:5)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1055:16)
    at Socket.<anonymous> (internal/child_process.js:441:11)
    at Socket.emit (events.js:400:28)
    at Pipe.<anonymous> (net.js:675:12)
`

The URL is 
`http://127.0.0.1:5001/solve?domain=http://www.haz.ca/planning-domains/classical/blocks/domain.pddl&problem=http://www.haz.ca/planning-domains/classical/blocks/probBLOCKS-4-1.pddl` 
and 
`https://safe-dusk-54737.herokuapp.com/solve?domain=http://www.haz.ca/planning-domains/classical/blocks/domain.pddl&problem=http://www.haz.ca/planning-domains/classical/blocks/probBLOCKS-4-1.pddl`

Any help?

**Comment by haz** [comment]
Kind of a shot in the dark, but it may be a node versioning issue? The heroku stack of stuff used for this (found [here](https://github.com/AI-Planning/cloud-solver/blob/master/package.json)) is quite dated.

If you're willing to shrug it off for now, there is a new project meant to replace this one entirely that we're putting the final touches on: https://github.com/AI-Planning/planning-as-a-service
